#!/usr/bin/env bash

set -euo pipefail

# invokes git command in all git directories found

GIT_DIRS=`find -L . -type d -name .git`
wd=`pwd`
for gitdir in $GIT_DIRS
do
  dir=`dirname $gitdir`
  cd $dir
  RESULT=`git --no-pager "$@"`
  if [ $? -eq 0 ]
  then
    echo ""; echo "$dir"
    echo "$RESULT"
  fi
  cd $wd
done
